spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wgyxydemo?useSSL=false
    username: root
    password: mynameis@
mybatis:
  config-location: classpath:mybatis.xml
debug: true
server:
  port: 8080
#spring.resources.static-locations=classpath:/testStatic/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
resources:
  static-locations:["/static/"]
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

